export const RESERVED_KEYWORDS = [
    "rubah", 
    "kalau", 
    "namun", 
    "slagi", 
    "untuk", 
    "cetak", 
    "henti", 
    "lewat", 
    "dalam", 
    "hasil", 
    "kerja", 
    "datum", 
    "jenis", 
    "model", 
    "error", 
    "tetap", 
    "modul", 
];

export const
    RUBAH = 0,
    KALAU = 1,
    NAMUN = 2,
    SLAGI = 3,
    UNTUK = 4,
    CETAK = 5,
    HENTI = 6,
    LEWAT = 7,
    DALAM = 8,
    HASIL = 9,
    KERJA = 10,
    DATUM = 11,
    JENIS = 12,
    MODEL = 13,
    ERROR = 14,
    TETAP = 15,
    MODUL = 16,
    EOF = 17,
    ID = 18,
    LITERAL = 19,
    PLUS = 20,
    MINUS = 21,
    STAR = 22,
    SLASH = 23,
    LPAREN = 24,
    RPAREN = 25,
    GREATER = 26,
    GREATER_EQUAL = 27,
    LESS = 28,
    LESS_EQUAL = 29,
    EQUAL = 30,
    EQUAL_EQUAL = 31,
    DOT = 32,
    LCURLY = 33,
    RCURLY = 34,
    COMMA = 35,
    LSQUARE = 36,
    RSQUARE = 37,
    PIPE = 38,
    AMPERSAND = 39,
    BANG = 40,
    ARROW = 41,
    BANG_EQUAL = 42,
    MODULUS = 43;

export const TOKEN_STRING = [
    "RUBAH", 
    "KALAU", 
    "NAMUN", 
    "SLAGI", 
    "UNTUK", 
    "CETAK", 
    "HENTI", 
    "LEWAT", 
    "DALAM", 
    "HASIL", 
    "KERJA", 
    "DATUM", 
    "JENIS", 
    "MODEL", 
    "ERROR", 
    "TETAP", 
    "MODUL", 
    "EOF",
    "ID",
    "LITERAL",
    "PLUS",
    "MINUS",
    "BINTANG",
    "GARIS_MIRING",
    "LPAREN",
    "RPAREN",
    "LEBIH",
    "LEBIH_SAMA",
    "KURANG",
    "KURANG_SAMA",
    "SAMA",
    "SAMA_SAMA",
    "DOT",
    "LCURLY",
    "RCURLY",
    "COMMA",
    "LSQUARE",
    "RSQUARE",
    "PIPA",
    "AMPERSAN",
    "SERU",
    "ARROW",
    "SERU_SAMA",
    "MODULUS",
];
