export const RESERVED_KEYWORDS = [
    "rubah", 
    "kalau", 
    "namun", 
    "slagi", 
    "untuk", 
    "cetak", 
    "henti", 
    "lewat", 
    "dalam", 
    "hasil", 
    "kerja", 
    "jenis", 
    "model", 
    "error", 
    "tetap", 
    "modul", 
];

export const
    RUBAH = 0,
    KALAU = 1,
    NAMUN = 2,
    SLAGI = 3,
    UNTUK = 4,
    CETAK = 5,
    HENTI = 6,
    LEWAT = 7,
    DALAM = 8,
    HASIL = 9,
    KERJA = 10,
    JENIS = 11,
    MODEL = 12,
    ERROR = 13,
    TETAP = 14,
    MODUL = 15,
    EOF = 16,
    ID = 17,
    LITERAL = 18,
    PLUS = 19,
    MINUS = 20,
    STAR = 21,
    SLASH = 22,
    LPAREN = 23,
    RPAREN = 24,
    GREATER = 25,
    GREATER_EQUAL = 26,
    LESS = 27,
    LESS_EQUAL = 28,
    EQUAL = 29,
    EQUAL_EQUAL = 30,
    DOT = 31,
    LCURLY = 32,
    RCURLY = 33,
    COMMA = 34,
    LSQUARE = 35,
    RSQUARE = 36,
    PIPE = 37,
    AMPERSAND = 38,
    BANG = 39,
    ARROW = 40,
    BANG_EQUAL = 41,
    MODULUS = 42;

export const TOKEN_STRING = [
    "RUBAH", 
    "KALAU", 
    "NAMUN", 
    "SLAGI", 
    "UNTUK", 
    "CETAK", 
    "HENTI", 
    "LEWAT", 
    "DALAM", 
    "HASIL", 
    "KERJA", 
    "JENIS", 
    "MODEL", 
    "ERROR", 
    "TETAP", 
    "MODUL", 
    "EOF",
    "ID",
    "LITERAL",
    "PLUS",
    "MINUS",
    "BINTANG",
    "GARIS_MIRING",
    "LPAREN",
    "RPAREN",
    "LEBIH",
    "LEBIH_SAMA",
    "KURANG",
    "KURANG_SAMA",
    "SAMA",
    "SAMA_SAMA",
    "DOT",
    "LCURLY",
    "RCURLY",
    "COMMA",
    "LSQUARE",
    "RSQUARE",
    "PIPA",
    "AMPERSAN",
    "SERU",
    "ARROW",
    "SERU_SAMA",
    "MODULUS",
];
