export const RESERVED_KEYWORDS = [
    "rubah", 
    "kalau", 
    "namun", 
    "slagi", 
    "untuk", 
    "cetak", 
    "henti", 
    "lewat", 
    "dalam", 
    "hasil", 
    "kerja", 
    "jenis", 
    "model", 
    "error", 
    "tetap", 
];

export const
    RUBAH = 0,
    KALAU = 1,
    NAMUN = 2,
    SLAGI = 3,
    UNTUK = 4,
    CETAK = 5,
    HENTI = 6,
    LEWAT = 7,
    DALAM = 8,
    HASIL = 9,
    KERJA = 10,
    JENIS = 11,
    MODEL = 12,
    ERROR = 13,
    TETAP = 14,
    EOF = 15,
    ID = 16,
    LITERAL = 17,
    PLUS = 18,
    MINUS = 19,
    STAR = 20,
    SLASH = 21,
    LPAREN = 22,
    RPAREN = 23,
    GREATER = 24,
    GREATER_EQUAL = 25,
    LESS = 26,
    LESS_EQUAL = 27,
    EQUAL = 28,
    EQUAL_EQUAL = 29,
    DOT = 30,
    LCURLY = 31,
    RCURLY = 32,
    COMMA = 33,
    LSQUARE = 34,
    RSQUARE = 35,
    PIPE = 36,
    AMPERSAND = 37,
    BANG = 38,
    ARROW = 39,
    BANG_EQUAL = 40,
    MODULUS = 41;

export const TOKEN_STRING = [
    "RUBAH", 
    "KALAU", 
    "NAMUN", 
    "SLAGI", 
    "UNTUK", 
    "CETAK", 
    "HENTI", 
    "LEWAT", 
    "DALAM", 
    "HASIL", 
    "KERJA", 
    "JENIS", 
    "MODEL", 
    "ERROR", 
    "TETAP", 
    "EOF",
    "ID",
    "LITERAL",
    "PLUS",
    "MINUS",
    "STAR",
    "SLASH",
    "LPAREN",
    "RPAREN",
    "GREATER",
    "GREATER_EQUAL",
    "LESS",
    "LESS_EQUAL",
    "EQUAL",
    "EQUAL_EQUAL",
    "DOT",
    "LCURLY",
    "RCURLY",
    "COMMA",
    "LSQUARE",
    "RSQUARE",
    "PIPE",
    "AMPERSAND",
    "BANG",
    "ARROW",
    "BANG_EQUAL",
    "MODULUS",
];
