export const RESERVED_KEYWORDS = [
    "rubah",
    "kalau",
    "namun",
    "slagi",
    "untuk",
    "cetak",
    "henti",
    "lewat",
    "dalam",
    "hasil",
    "kerja",
    "datum",
    "jenis",
    "model",
    "tetap",
    "modul",
    "lihat",
    "kasus",
    "jatuh",
];

export const
    RUBAH = 0,
    KALAU = 1,
    NAMUN = 2,
    SLAGI = 3,
    UNTUK = 4,
    CETAK = 5,
    HENTI = 6,
    LEWAT = 7,
    DALAM = 8,
    HASIL = 9,
    KERJA = 10,
    DATUM = 11,
    JENIS = 12,
    MODEL = 13,
    TETAP = 14,
    MODUL = 15,
    LIHAT = 16,
    KASUS = 17,
    JATUH = 18,
    EOF = 19,
    ID = 20,
    LITERAL = 21,
    PLUS = 22,
    MINUS = 23,
    STAR = 24,
    SLASH = 25,
    LPAREN = 26,
    RPAREN = 27,
    GREATER = 28,
    GREATER_EQUAL = 29,
    LESS = 30,
    LESS_EQUAL = 31,
    EQUAL = 32,
    EQUAL_EQUAL = 33,
    DOT = 34,
    LCURLY = 35,
    RCURLY = 36,
    COMMA = 37,
    LSQUARE = 38,
    RSQUARE = 39,
    PIPE = 40,
    AMPERSAND = 41,
    BANG = 42,
    ARROW = 43,
    BANG_EQUAL = 44,
    MODULUS = 45,
    PIPELINE = 46,
    COLON = 47,
    DOLLAR = 48;

export const TOKEN_STRING = [
    "RUBAH",
    "KALAU",
    "NAMUN",
    "SLAGI",
    "UNTUK",
    "CETAK",
    "HENTI",
    "LEWAT",
    "DALAM",
    "HASIL",
    "KERJA",
    "DATUM",
    "JENIS",
    "MODEL",
    "TETAP",
    "MODUL",
    "LIHAT",
    "KASUS",
    "JATUH",
    "EOF",
    "ID",
    "LITERAL",
    "PLUS",
    "MINUS",
    "BINTANG",
    "GARIS_MIRING",
    "LPAREN",
    "RPAREN",
    "LEBIH",
    "LEBIH_SAMA",
    "KURANG",
    "KURANG_SAMA",
    "SAMA",
    "SAMA_SAMA",
    "DOT",
    "LCURLY",
    "RCURLY",
    "COMMA",
    "LSQUARE",
    "RSQUARE",
    "PIPA",
    "AMPERSAN",
    "SERU",
    "ARROW",
    "SERU_SAMA",
    "MODULUS",
    "PIPELINE",
    "COLON",
    "DOLLAR",
];
