export const RESERVED_KEYWORDS = [
    "rubah",
    "kalau",
    "namun",
    "slagi",
    "untuk",
    "cetak",
    "henti",
    "lewat",
    "dalam",
    "hasil",
    "kerja",
    "datum",
    "jenis",
    "model",
    "tetap",
    "modul",
    "lihat",
    "kasus",
];

export const
    RUBAH = 0,
    KALAU = 1,
    NAMUN = 2,
    SLAGI = 3,
    UNTUK = 4,
    CETAK = 5,
    HENTI = 6,
    LEWAT = 7,
    DALAM = 8,
    HASIL = 9,
    KERJA = 10,
    DATUM = 11,
    JENIS = 12,
    MODEL = 13,
    TETAP = 14,
    MODUL = 15,
    LIHAT = 16,
    KASUS = 17,
    EOF = 18,
    ID = 19,
    LITERAL = 20,
    PLUS = 21,
    MINUS = 22,
    STAR = 23,
    SLASH = 24,
    LPAREN = 25,
    RPAREN = 26,
    GREATER = 27,
    GREATER_EQUAL = 28,
    LESS = 29,
    LESS_EQUAL = 30,
    EQUAL = 31,
    EQUAL_EQUAL = 32,
    DOT = 33,
    LCURLY = 34,
    RCURLY = 35,
    COMMA = 36,
    LSQUARE = 37,
    RSQUARE = 38,
    PIPE = 39,
    AMPERSAND = 40,
    BANG = 41,
    ARROW = 42,
    BANG_EQUAL = 43,
    MODULUS = 44,
    PIPELINE = 45,
    COLON = 46,
    DOLLAR = 47;

export const TOKEN_STRING = [
    "RUBAH",
    "KALAU",
    "NAMUN",
    "SLAGI",
    "UNTUK",
    "CETAK",
    "HENTI",
    "LEWAT",
    "DALAM",
    "HASIL",
    "KERJA",
    "DATUM",
    "JENIS",
    "MODEL",
    "TETAP",
    "MODUL",
    "LIHAT",
    "KASUS",
    "EOF",
    "ID",
    "LITERAL",
    "PLUS",
    "MINUS",
    "BINTANG",
    "GARIS_MIRING",
    "LPAREN",
    "RPAREN",
    "LEBIH",
    "LEBIH_SAMA",
    "KURANG",
    "KURANG_SAMA",
    "SAMA",
    "SAMA_SAMA",
    "DOT",
    "LCURLY",
    "RCURLY",
    "COMMA",
    "LSQUARE",
    "RSQUARE",
    "PIPA",
    "AMPERSAN",
    "SERU",
    "ARROW",
    "SERU_SAMA",
    "MODULUS",
    "PIPELINE",
    "COLON",
    "DOLLAR",
];
